services:
  - type: web
    name: sars-app
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: ./sars
    healthCheckPath: /
    
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Djava.net.preferIPv4Stack=true"
      - key: SERVER_PORT
        value: "8080"

      - key: DB_HOST
        fromDatabase:
          name: sars-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sars-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: sars-db
          property: databaseName
      - key: DB_USER
        fromDatabase:
          name: sars-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sars-db
          property: password

      # DDL Auto para producci√≥n
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: sars-db
    databaseName: sars
    user: user
    plan: free
    region: frankfurt
