services:
  - type: web
    name: sars-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./sars
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: sars-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: sars-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: sars-db
          property: password
      
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SERVER_PORT
        value: 8080

databases:
  - name: sars-db
    databaseName: sars
    user: user
    plan: free # Recuerda: se borra a los 90 días si no pagas, perfecto para pruebas
    region: frankfurt # Elige la región más cercana (oregon, frankfurt, etc.)
