services:
  - type: web
    name: sars-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./sars
    
    healthCheckPath: /
    
envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://sars-db:5432/sars

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: sars-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: sars-db
          property: password

      - key: SPRING_DATASOURCE_LAZY_INITIALIZATION
        value: "true"
      
      - key: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
        value: "-1"
      - key: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
        value: "60000"
      
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SERVER_PORT
        value: 8080

databases:
  - name: sars-db
    databaseName: sars
    user: user
    plan: free
    region: frankfurt
