services:
  - type: web
    name: sars-app
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: ./sars
    
    healthCheckPath: /
    
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Djava.net.preferIPv4Stack=true"

      - key: PORT
        value: "8080"
      - key: SERVER_PORT
        value: "8080"
      
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://sars-db:5432/sars?sslmode=disable
        
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: sars-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: sars-db
          property: password
          
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: sars-db
    databaseName: sars
    user: user
    plan: free
    region: frankfurt
